import { Prisma } from "@prisma/client";

const imgFem = "http://e00-ar-marca.uecdn.es/claro/assets/multimedia/imagenes/2019/06/10/15601767026611.jpg";
const imgMal = "https://elcomercio.pe/resizer/HaSt-OxS5Ka1U3uIdvTtb0UccSQ=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/YOBYBB2WL5CQFEP553TMA6CKV4.png";

const users: Prisma.UserCreateInput[] = [
  {
		name: "Jorden Dodson",
		userName: "Jorden",
		dni: 31719083,
		gender: "MALE",
		birthday: "31/07/1989",
		cellphone: 6459392576,
		mail: "integer@etarcu.edu",
		image: imgMal,
		password: "VLR23NVW1XW",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 20,
        votes: 4,
        available: true,
      },
    },
	},
	{
		name: "Sigourney Tyson",
		userName: "Sigourney Tyler",
		dni: 41461934,
		gender: "MALE",
		birthday: "20/06/1977",
		cellphone: 9308517979,
		mail: "ad.litora.torquent@libero.org",
		image: imgMal,
		password: "TSO42FSM5YF",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 22,
        votes: 5,
        available: true,
      },
    },
	},
	{
		name: "Willa Howe",
		userName: "Willa",
		dni: 43505263,
		gender: "FEMALE",
		birthday: "10/07/1984",
		cellphone: 6301166860,
		mail: "diam.at@egetvolutpatornare.net",
		image: imgFem,
		password: "KSC34RUD8WK",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 22,
        votes: 6,
      },
    },
	},
	{
		name: "Yoko Estes",
		userName: "Yoko",
		dni: 49282062,
		gender: "FEMALE",
		birthday: "21/03/1977",
		cellphone: 3171547077,
		mail: "felis.ullamcorper@laciniased.ca",
		image: imgFem,
		password: "PCF18OVC7TB",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 28,
        votes: 7,
        available: true,
      },
    },
	},
	{
		name: "Bertha Hammond",
		userName: "Bertha",
		dni: 16547386,
		gender: "FEMALE",
		birthday: "20/08/1986",
		cellphone: 9391772973,
		mail: "nunc@nisisemsemper.com",
		image: imgFem,
		password: "LBF94UDG2SO",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 20,
        votes: 4,
      },
    },
	},
  {
		name: "Abdul Callahan",
		userName: "Herrod Gilmore",
		dni: 45965804,
		gender: "MALE",
		birthday: "07/01/2000",
		cellphone: 6208158294,
		mail: "sapien.aenean@sagittisduisgravida.co.uk",
		image: imgMal,
		password: "UHM62YPJ8EP",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 16,
        votes: 5,
      },
    },
	},
	{
		name: "Craig Bishop",
		userName: "Craig",
		dni: 13339241,
		gender: "MALE",
		birthday: "22/04/1990",
		cellphone: 7046798295,
		mail: "diam.pellentesque@convallisestvitae.com",
		image: imgMal,
		password: "JFG84VQC3TV",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Jerome Frank",
		userName: "Jerome",
		dni: 28713237,
		gender: "MALE",
		birthday: "08/07/1987",
		cellphone: 4412084711,
		mail: "rutrum.fusce@nulla.net",
		image: imgMal,
		password: "YQZ78CMB1JP",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 22,
        votes: 6,
      },
    },
	},
	{
		name: "Riley James",
		userName: "Riley",
		dni: 19899553,
		gender: "FEMALE",
		birthday: "20/12/1988",
		cellphone: 5941755431,
		mail: "libero.proin@integerid.org",
		image: imgFem,
		password: "XAE45REZ4OG",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 32,
        votes: 9,
      },
    },
	},
	{
		name: "Zeus Robbins",
		userName: "Zeus",
		dni: 35256348,
		gender: "MALE",
		birthday: "04/05/1998",
		cellphone: 2278541146,
		mail: "dictum.augue.malesuada@atarcu.ca",
		image: imgMal,
		password: "MLO95SCT3JU",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 20,
        votes: 4,
        available: true,
      },
    },
	},
  {
		name: "Hadley Dennis",
		userName: "Hadley",
		dni: 38860749,
		gender: "MALE",
		birthday: "24/08/1980",
		cellphone: 2023260571,
		mail: "gravida@tellusjusto.net",
		image: imgMal,
		password: "NVJ47XCI0NP",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 28,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Malik Solomon",
		userName: "Malik",
		dni: 37307393,
		gender: "MALE",
		birthday: "03/08/1974",
		cellphone: 7401047825,
		mail: "adipiscing.non.luctus@aliquet.ca",
		image: imgMal,
		password: "WUW24XSE0IJ",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 26,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Ruby Mays",
		userName: "Ruby",
		dni: 13134541,
		gender: "MALE",
		birthday: "21/05/1982",
		cellphone: 1910719008,
		mail: "eget@sociosquad.com",
		image: imgMal,
		password: "TOG33UVK5BC",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 24,
        votes: 8,
      },
    },
	},
	{
		name: "Thaddeus Wise",
		userName: "Thaddeus",
		dni: 25269754,
		gender: "MALE",
		birthday: "25/11/1974",
		cellphone: 8778771918,
		mail: "posuere.vulputate.lacus@nullamenim.edu",
		image: imgMal,
		password: "EOO97KED7LS",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Florence Rich",
		userName: "Florence",
		dni: 19428362,
		gender: "FEMALE",
		birthday: "03/05/1979",
		cellphone: 1316216720,
		mail: "integer@milorem.co.uk",
		image: imgFem,
		password: "MVS13TVC6RS",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 32,
        votes: 8,
      },
    },
	},
  {
		name: "Harlan Walton",
		userName: "Harlan",
		dni: 27364108,
		gender: "MALE",
		birthday: "09/01/1986",
		cellphone: 6023018560,
		mail: "purus.nullam@velarcu.com",
		image: imgMal,
		password: "JDY71UJV3CK",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 30,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Megan Dennis",
		userName: "Megan",
		dni: 13191362,
		gender: "FEMALE",
		birthday: "06/04/1974",
		cellphone: 6463662364,
		mail: "facilisis@tristiqueneque.com",
		image: imgFem,
		password: "SJP02YMQ8XH",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 28,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Desiree Underwood",
		userName: "Desiree",
		dni: 16028315,
		gender: "MALE",
		birthday: "17/06/1974",
		cellphone: 2606178462,
		mail: "facilisis@nuncsit.org",
		image: imgMal,
		password: "DUV28OWN6JU",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 26,
        votes: 8,
      },
    },
	},
	{
		name: "Jeremy Crane",
		userName: "Jeremy",
		dni: 22606174,
		gender: "MALE",
		birthday: "13/10/1985",
		cellphone: 2291257917,
		mail: "nostra.per@adipiscing.ca",
		image: imgMal,
		password: "XUD81QFZ4DZ",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 24,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Shelby Hensley",
		userName: "Shelby",
		dni: 17166167,
		gender: "FEMALE",
		birthday: "29/04/1973",
		cellphone: 2495480784,
		mail: "non@auguescelerisque.edu",
		image: imgFem,
		password: "ABO67QUT1IL",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Ryder Ochoa",
		userName: "Ryder",
		dni: 40525558,
		gender: "FEMALE",
		birthday: "03/03/1978",
		cellphone: 7732526581,
		mail: "volutpat@eratin.com",
		image: imgFem,
		password: "EUJ01XLR6JF",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Valentine Lara",
		userName: "Valentine",
		dni: 31566032,
		gender: "MALE",
		birthday: "15/12/1985",
		cellphone: 1395863626,
		mail: "elit@faucibusidlibero.edu",
		image: imgMal,
		password: "SHY45OHJ7OH",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 32,
        votes: 8,
      },
    },
	},
	{
		name: "Oren Perkins",
		userName: "Oren",
		dni: 24279594,
		gender: "MALE",
		birthday: "15/06/1992",
		cellphone: 3675410049,
		mail: "at@nuncrisusvarius.ca",
		image: imgMal,
		password: "CTQ05GBQ7PN",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Alvin Moss",
		userName: "Alvin",
		dni: 17649665,
		gender: "MALE",
		birthday: "12/03/2000",
		cellphone: 6197001075,
		mail: "nunc.est.mollis@est.ca",
		image: imgMal,
		password: "OKG84NDF8OI",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 20,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Warren Wright",
		userName: "Warren",
		dni: 15569429,
		gender: "MALE",
		birthday: "04/10/1981",
		cellphone: 8012820655,
		mail: "tempor@fuscefeugiat.com",
		image: imgMal,
		password: "LXE58BFB7FU",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 22,
        votes: 8,
      },
    },
	},
  {
		name: "Aphrodite Clarke",
		userName: "Aphrodite",
		dni: 20067935,
		gender: "FEMALE",
		birthday: "10/12/1980",
		cellphone: 4402888963,
		mail: "eleifend.egestas.sed@rutrumnon.net",
		image: imgFem,
		password: "UUI36HGP2OU",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 24,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Zephania Underwood",
		userName: "Zephania",
		dni: 46048514,
		gender: "FEMALE",
		birthday: "12/03/1975",
		cellphone: 8120092231,
		mail: "pede.et@sapiencras.edu",
		image: imgFem,
		password: "RBF14IBZ8HV",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 26,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Randall Barker",
		userName: "Randall",
		dni: 36309579,
		gender: "MALE",
		birthday: "14/09/1995",
		cellphone: 3046038264,
		mail: "ante.dictum@proin.edu",
		image: imgMal,
		password: "VPN76TFR2VT",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 38,
        votes: 8,
      },
    },
	},
	{
		name: "Allegra Mccarthy",
		userName: "Allegra",
		dni: 48431884,
		gender: "FEMALE",
		birthday: "27/01/1987",
		cellphone: 3718959528,
		mail: "magnis.dis@ullamcorper.net",
		image: imgFem,
		password: "GNH73WGD7VP",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 30,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "William Gonzales",
		userName: "William",
		dni: 17435793,
		gender: "MALE",
		birthday: "24/01/1988",
		cellphone: 7039613491,
		mail: "a.ultricies@enimmauris.edu",
		image: imgMal,
		password: "DHB53UPQ6VL",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Fletcher Stephens",
		userName: "Fletcher",
		dni: 36845214,
		gender: "MALE",
		birthday: "06/04/1988",
		cellphone: 6756642940,
		mail: "eget.venenatis.a@senectuset.com",
		image: imgMal,
		password: "SFP33WMJ7WT",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 32,
        votes: 8,
      },
    },
	},
	{
		name: "Quynn Roy",
		userName: "Quynn",
		dni: 16672525,
		gender: "MALE",
		birthday: "06/04/1988",
		cellphone: 3806147888,
		mail: "et.commodo@fringillaeuismod.ca",
		image: imgMal,
		password: "XPO42PVK4YB",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 32,
        votes: 8,
      },
    },
	},
	{
		name: "Brynn Joseph",
		userName: "Brynn",
		dni: 45565294,
		gender: "MALE",
		birthday: "24/08/1998",
		cellphone: 3404592860,
		mail: "mauris.quis@nunccommodoauctor.edu",
		image: imgMal,
		password: "UMR62FSM7UA",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Ana Downs",
		userName: "Ana",
		dni: 18148834,
		gender: "FEMALE",
		birthday: "02/02/1975",
		cellphone: 4915651752,
		mail: "mauris@ante.ca",
		image: imgFem,
		password: "TCV16VNK3EK",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Ginger Bauer",
		userName: "Ginger",
		dni: 36807678,
		gender: "FEMALE",
		birthday: "25/01/1988",
		cellphone: 5726576117,
		mail: "lorem.tristique.aliquet@tristique.net",
		image: imgFem,
		password: "KNV32EPQ6LD",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 30,
        votes: 8,
      },
    },
	},
  {
		name: "Nathan Wilcox",
		userName: "Nathan",
		dni: 44621874,
		gender: "MALE",
		birthday: "07/12/1993",
		cellphone: 2454489606,
		mail: "tempus.lorem@donecestnunc.co.uk",
		image: imgMal,
		password: "CNR74TCX7LH",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 15,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Ciara Summers",
		userName: "Ciara",
		dni: 31137579,
		gender: "FEMALE",
		birthday: "28/02/1972",
		cellphone: 9757643127,
		mail: "dolor.nonummy.ac@sedtortorinteger.com",
		image: imgFem,
		password: "FTF75DXV9GZ",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 14,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Destiny Freeman",
		userName: "Destiny",
		dni: 32787837,
		gender: "FEMALE",
		birthday: "22/08/1977",
		cellphone: 8448667148,
		mail: "sed@orciluctus.net",
		image: imgFem,
		password: "XUH25TTO2KS",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 30,
        votes: 8,
      },
    },
	},
	{
		name: "Vanna Heath",
		userName: "Vanna",
		dni: 18479147,
		gender: "FEMALE",
		birthday: "24/06/1999",
		cellphone: 6325325924,
		mail: "sociosqu.ad@conubianostra.edu",
		image: imgFem,
		password: "QMU92LLW5RA",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 29,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Lucas Graves",
		userName: "Lucas",
		dni: 48359017,
		gender: "MALE",
		birthday: "12/06/1981",
		cellphone: 1276308066,
		mail: "enim.etiam@acfermentum.org",
		image: imgMal,
		password: "XDJ25IDV2BX",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 28,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Carter Cook",
		userName: "Carter",
		dni: 47068585,
		gender: "MALE",
		birthday: "25/05/1992",
		cellphone: 4383622751,
		mail: "non.nisi@asollicitudin.com",
		image: imgMal,
		password: "DRW32MPT6SX",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 27,
        votes: 8,
      },
    },
	},
	{
		name: "Chiquita Wagner",
		userName: "Chiquita",
		dni: 49098575,
		gender: "FEMALE",
		birthday: "14/03/1974",
		cellphone: 4567707676,
		mail: "egestas.aliquam.nec@etmagnisdis.co.uk",
		image: imgFem,
		password: "SPH20LNW1QN",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 26,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Hayes Miles",
		userName: "Hayes",
		dni: 40947818,
		gender: "MALE",
		birthday: "12/09/2000",
		cellphone: 7340014357,
		mail: "donec.consectetuer.mauris@sed.org",
		image: imgMal,
		password: "OTC67RTQ3HB",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 25,
        votes: 8,
      },
    },
	},
	{
		name: "Acton Cline",
		userName: "Acton",
		dni: 33118934,
		gender: "MALE",
		birthday: "25/06/1982",
		cellphone: 4378417853,
		mail: "sem.eget.massa@in.edu",
		image: imgMal,
		password: "NWU83QBM7EJ",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 24,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Mallory Jenkins",
		userName: "Mallory",
		dni: 44949164,
		gender: "FEMALE",
		birthday: "01/08/1997",
		cellphone: 4554423110,
		mail: "auctor.non.feugiat@nuncquisque.edu",
		image: imgFem,
		password: "FLM78VXG9IN",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 23,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Finn Gomez",
		userName: "Finn",
		dni: 48304801,
		gender: "MALE",
		birthday: "18/06/1983",
		cellphone: 2056532136,
		mail: "nibh.lacinia@musproin.com",
		image: imgMal,
		password: "RTL69QMZ8OY",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 22,
        votes: 8,
      },
    },
	},
	{
		name: "Troy Stevenson",
		userName: "Troy",
		dni: 14433125,
		gender: "MALE",
		birthday: "11/11/1973",
		cellphone: 8905422350,
		mail: "sed.congue@elitfermentum.net",
		image: imgMal,
		password: "WRI45QSJ9PM",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 21,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Channing Mcleod",
		userName: "Channing",
		dni: 38101026,
		gender: "MALE",
		birthday: "18/12/1976",
		cellphone: 3404746667,
		mail: "purus.maecenas.libero@integeraliquam.com",
		image: imgMal,
		password: "QAY55VVT4LT",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 20,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Brittany Coffey",
		userName: "Brittany",
		dni: 22242572,
		gender: "FEMALE",
		birthday: "05/11/1985",
		cellphone: 9789577004,
		mail: "neque.pellentesque@ultricesposuere.net",
		image: imgFem,
		password: "XHL43TMM0RO",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 19,
        votes: 8,
      },
    },
	},
	{
		name: "Porter Flores",
		userName: "Porter",
		dni: 30690925,
		gender: "MALE",
		birthday: "24/06/2000",
		cellphone: 8608464858,
		mail: "quis@elitpede.com",
		image: imgMal,
		password: "TWH70CYK1CS",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 18,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Melodie Rich",
		userName: "Melodie",
		dni: 15360119,
		gender: "FEMALE",
		birthday: "24/10/1997",
		cellphone: 8379361361,
		mail: "mus.proin@turpisnonenim.edu",
		image: imgFem,
		password: "REF19UZN0JI",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 17,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Yeo Wall",
		userName: "Yeo",
		dni: 30005860,
		gender: "MALE",
		birthday: "17/01/1971",
		cellphone: 2364904123,
		mail: "mauris@augueporttitor.net",
		image: imgMal,
		password: "EGD62BQC8EP",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 16,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Kimberly Mooney",
		userName: "Kimberly",
		dni: 14371339,
		gender: "FEMALE",
		birthday: "27/05/1973",
		cellphone: 5018685931,
		mail: "amet@risusat.org",
		image: imgFem,
		password: "SHQ31OUL4XL",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 32,
        votes: 8,
      },
    },
	},
	{
		name: "Barry Hicks",
		userName: "Barry",
		dni: 36606005,
		gender: "MALE",
		birthday: "19/07/1978",
		cellphone: 5529528360,
		mail: "est.mauris.eu@atpretiumaliquet.com",
		image: imgMal,
		password: "WVW46UDU5PP",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 30,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Hedy Meyers",
		userName: "Hedy",
		dni: 22998165,
		gender: "MALE",
		birthday: "28/02/1998",
		cellphone: 5900708010,
		mail: "mi@quis.net",
		image: imgMal,
		password: "MYE72QYV0QI",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 29,
        votes: 8,
      },
    },
	},
  {
		name: "Alexa Horn",
		userName: "Alexa",
		dni: 45487598,
		gender: "FEMALE",
		birthday: "18/10/1976",
		cellphone: 4084526333,
		mail: "proin.non@egestasligula.co.uk",
		image: imgFem,
		password: "RON86GWK4UR",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 28,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Kibo Newton",
		userName: "Kibo",
		dni: 17273907,
		gender: "MALE",
		birthday: "12/07/1987",
		cellphone: 7832439991,
		mail: "enim.etiam@vel.ca",
		image: imgMal,
		password: "GRM70SKP8KE",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 27,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Blaze Farrell",
		userName: "Blaze",
		dni: 31208712,
		gender: "MALE",
		birthday: "28/10/1993",
		cellphone: 8136903508,
		mail: "phasellus.vitae.mauris@inscelerisque.com",
		image: imgMal,
		password: "RYM27XVB5TV",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 26,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Peter Pate",
		userName: "Peter",
		dni: 29884642,
		gender: "MALE",
		birthday: "22/12/1971",
		cellphone: 6182465171,
		mail: "diam.sed@diamvel.edu",
		image: imgMal,
		password: "UDH74ELE7YY",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 25,
        votes: 8,
      },
    },
	},
	{
		name: "Erin Campos",
		userName: "Erin",
		dni: 43141853,
		gender: "MALE",
		birthday: "19/07/1979",
		cellphone: 1672407062,
		mail: "a.odio@rutrumfusce.ca",
		image: imgMal,
		password: "INL96FUO7VP",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 24,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Jesus Goodman",
		userName: "Jesus",
		dni: 17627163,
		gender: "MALE",
		birthday: "08/09/1972",
		cellphone: 4207000855,
		mail: "sagittis.lobortis@inornare.com",
		image: imgMal,
		password: "VIZ87EBF8EV",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 23,
        votes: 8,
      },
    },
	},
	{
		name: "Anthony Pacheco",
		userName: "Anthony",
		dni: 25515462,
		gender: "FEMALE",
		birthday: "25/04/1985",
		cellphone: 3619640468,
		mail: "nec@adipiscinglobortis.net",
		image: imgFem,
		password: "APT62HIR3JF",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 22,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Orlando Eaton",
		userName: "Orlando",
		dni: 40453594,
		gender: "MALE",
		birthday: "30/05/1994",
		cellphone: 3223218610,
		mail: "ante.blandit@ipsumsuspendissenon.com",
		image: imgMal,
		password: "FPC72HDX8YD",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 21,
        votes: 8,
      },
    },
	},
	{
		name: "Sonya Black",
		userName: "Sonya",
		dni: 25805301,
		gender: "FEMALE",
		birthday: "15/03/1999",
		cellphone: 3822033217,
		mail: "sodales.elit.erat@nonluctus.net",
		image: imgFem,
		password: "TSS73RCC5PL",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 20,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Luis Matthews",
		userName: "Luis",
		dni: 46612395,
		gender: "MALE",
		birthday: "11/12/1977",
		cellphone: 9286963462,
		mail: "consequat.lectus@eratvolutpat.org",
		image: imgMal,
		password: "ARN21BWD9HG",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 18,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Nash Valdez",
		userName: "Nash",
		dni: 38621425,
		gender: "MALE",
		birthday: "16/02/1983",
		cellphone: 1396031394,
		mail: "ullamcorper.velit.in@purusmaecenaslibero.edu",
		image: imgMal,
		password: "PGC36LVF6ZJ",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 16,
        votes: 8,
      },
    },
	},
	{
		name: "Ruth Allen",
		userName: "Ruth",
		dni: 43116634,
		gender: "FEMALE",
		birthday: "02/07/1995",
		cellphone: 6326778517,
		mail: "morbi@quampellentesque.org",
		image: imgFem,
		password: "GFD85QNV8OK",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 32,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Christian Park",
		userName: "Christian",
		dni: 43050861,
		gender: "MALE",
		birthday: "30/11/1975",
		cellphone: 8123694051,
		mail: "sodales.mauris@sagittis.edu",
		image: imgMal,
		password: "YRO37EDP6EO",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 30,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Clarke Jackson",
		userName: "Clarke",
		dni: 20187921,
		gender: "MALE",
		birthday: "24/10/1981",
		cellphone: 1492718561,
		mail: "id.risus@consequatenim.co.uk",
		image: imgMal,
		password: "DZN29PWW2TB",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 28,
        votes: 8,
      },
    },
	},
	{
		name: "Daniel Wilson",
		userName: "Daniel",
		dni: 17845699,
		gender: "MALE",
		birthday: "20/01/1992",
		cellphone: 9827226920,
		mail: "nunc.in.at@nunclaoreetlectus.ca",
		image: imgMal,
		password: "WTV64KTH1EX",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 26,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Quinn Horne",
		userName: "Quinn",
		dni: 35398147,
		gender: "FEMALE",
		birthday: "21/12/1980",
		cellphone: 6586138155,
		mail: "dictum.magna.ut@nullacraseu.net",
		image: imgFem,
		password: "ITF89QYL0JK",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 24,
        votes: 8,
      },
    },
	},
	{
		name: "Colin Fleming",
		userName: "Colin",
		dni: 26065097,
		gender: "MALE",
		birthday: "23/07/1992",
		cellphone: 1649346817,
		mail: "est@egestasrhoncusproin.ca",
		image: imgMal,
		password: "GBU80QBV6DG",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 20,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Kelly Ferguson",
		userName: "Kelly",
		dni: 34847223,
		gender: "FEMALE",
		birthday: "03/12/1982",
		cellphone: 5805350496,
		mail: "arcu.eu.odio@suspendisse.com",
		image: imgFem,
		password: "MTE87BJW4DC",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 18,
        votes: 8,
      },
    },
	},
	{
		name: "Jelani Hendrix",
		userName: "Jelani",
		dni: 37460729,
		gender: "FEMALE",
		birthday: "08/12/1978",
		cellphone: 2979453535,
		mail: "ultricies.ornare@egetmetus.net",
		image: imgFem,
		password: "BJX96RXR4RW",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 36,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Jonas Roy",
		userName: "Jonas",
		dni: 27416611,
		gender: "MALE",
		birthday: "22/10/1970",
		cellphone: 3234384910,
		mail: "nisi.a@loremipsum.edu",
		image: imgMal,
		password: "PDG78BLO8SP",
    player: {
      create: {
        position: "MIDFIELDER",
        qualification: 34,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Camilla Cabrera",
		userName: "Camilla",
		dni: 31006064,
		gender: "FEMALE",
		birthday: "11/04/1976",
		cellphone: 8286883505,
		mail: "aliquam.ornare@orcilobortisaugue.com",
		image: imgFem,
		password: "TJQ94CFX5RZ",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 32,
        votes: 8,
      },
    },
	},
	{
		name: "Stephen Clemons",
		userName: "Stephen",
		dni: 14590169,
		gender: "MALE",
		birthday: "27/07/1989",
		cellphone: 3406969285,
		mail: "enim.non.nisi@anteipsumprimis.org",
		image: imgMal,
		password: "IVD59EZE2SW",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 30,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Nita Talley",
		userName: "Nita",
		dni: 17455880,
		gender: "FEMALE",
		birthday: "25/01/1990",
		cellphone: 1375613131,
		mail: "metus.aliquam@cumsociis.org",
		image: imgFem,
		password: "NJT24WDO1XC",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 28,
        votes: 8,
      },
    },
	},
	{
		name: "Larissa Cardenas",
		userName: "Larissa",
		dni: 28407301,
		gender: "FEMALE",
		birthday: "12/08/1974",
		cellphone: 6357185448,
		mail: "aliquam.eros@egetmagna.edu",
		image: imgFem,
		password: "QMV18MSR9EC",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 26,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Rhoda Watts",
		userName: "Rhoda",
		dni: 33828364,
		gender: "FEMALE",
		birthday: "21/02/1999",
		cellphone: 1618574602,
		mail: "euismod.urna.nullam@commodoauctorvelit.edu",
		image: imgFem,
		password: "PDI76QLJ0VN",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 24,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Lara Campbell",
		userName: "Lara",
		dni: 17225763,
		gender: "FEMALE",
		birthday: "13/12/1979",
		cellphone: 1124803915,
		mail: "velit.egestas.lacinia@vehiculaaliquet.net",
		image: imgFem,
		password: "UKE34IJU4UM",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 20,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Marny Sanders",
		userName: "Marny",
		dni: 13735832,
		gender: "FEMALE",
		birthday: "17/06/1971",
		cellphone: 9472632284,
		mail: "ligula.donec@urnanunc.co.uk",
		image: imgFem,
		password: "KWQ56HQZ4KX",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 18,
        votes: 8,
      },
    },
	},
	{
		name: "Anne Holmes",
		userName: "Anne",
		dni: 41191893,
		gender: "FEMALE",
		birthday: "16/02/1978",
		cellphone: 5638601203,
		mail: "auctor.quis@nequesed.co.uk",
		image: imgFem,
		password: "RKH17NXS5SW",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 24,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Marah Daugherty",
		userName: "Marah",
		dni: 40688119,
		gender: "FEMALE",
		birthday: "03/03/1985",
		cellphone: 8815639934,
		mail: "ultricies.sem@faucibusut.org",
		image: imgFem,
		password: "IYC78PIV8PC",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 30,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Megan Kirby",
		userName: "Megan",
		dni: 41763492,
		gender: "FEMALE",
		birthday: "13/04/1998",
		cellphone: 6883562862,
		mail: "libero.et@nonbibendum.edu",
		image: imgFem,
		password: "MDJ15XVY2WQ",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 27,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Linda Hernandez",
		userName: "Linda",
		dni: 39668831,
		gender: "FEMALE",
		birthday: "02/04/1979",
		cellphone: 5228182918,
		mail: "gravida.praesent@commodo.edu",
		image: imgFem,
		password: "MCD80FXL4AQ",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 24,
        votes: 8,
      },
    },
	},
	{
		name: "Katelyn Rich",
		userName: "Katelyn",
		dni: 43069314,
		gender: "FEMALE",
		birthday: "21/03/1972",
		cellphone: 8583560998,
		mail: "morbi.accumsan@nuncrisusvarius.co.uk",
		image: imgFem,
		password: "OGF22KCG1JZ",
    player: {
      create: {
        position: "GOALKEEPER",
        qualification: 37,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Allistair Navarro",
		userName: "Allistair",
		dni: 20319239,
		gender: "FEMALE",
		birthday: "12/07/1987",
		cellphone: 7946469185,
		mail: "praesent.eu@lectusa.org",
		image: imgFem,
		password: "DGY80FBC6FC",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 35,
        votes: 8,
        available: true,
      },
    },
	},
  {
		name: "Freya Hurley",
		userName: "Freya",
		dni: 21910794,
		gender: "FEMALE",
		birthday: "03/10/1975",
		cellphone: 7242116318,
		mail: "dignissim.magna.a@massavestibulumaccumsan.org",
		image: imgFem,
		password: "IAW86YQB6SR",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 26,
        votes: 8,
      },
    },
	},
	{
		name: "Len Snider",
		userName: "Len",
		dni: 45489337,
		gender: "MALE",
		birthday: "27/11/1988",
		cellphone: 1180225292,
		mail: "arcu@enimnectempus.net",
		image: imgMal,
		password: "CKE63NCN7LD",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 28,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Jelani Stevens",
		userName: "Jelani",
		dni: 20100153,
		gender: "FEMALE",
		birthday: "14/04/1998",
		cellphone: 2295519613,
		mail: "vulputate.lacus@velitcras.co.uk",
		image: imgFem,
		password: "VTU82DFH2NQ",
    player: {
      create: {
        position: "ATTACKER",
        qualification: 34,
        votes: 8,
        available: true,
      },
    },
	},
	{
		name: "Walker Burt",
		userName: "Walker",
		dni: 21472762,
		gender: "MALE",
		birthday: "31/05/1979",
		cellphone: 7256577639,
		mail: "ac.mattis@nonnisi.com",
		image: imgMal,
		password: "IDH71KWN2TD",
    player: {
      create: {
        position: "DEFENDER",
        qualification: 35,
        votes: 8,
        available: true,
      },
    },
	}
];

export default users